// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS76bX_zsTr6PDuTt6-7msWFmcCh_ar0w',
    appId: '1:97884437874:web:01d87db12a83a473da71eb',
    messagingSenderId: '97884437874',
    projectId: 'fir-flutter-codelab-44bee',
    authDomain: 'fir-flutter-codelab-44bee.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-44bee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGBAESKTU4FQJwM1qINpeE0QcEzC2X_8',
    appId: '1:97884437874:android:4ffa0b14e1d3c03fda71eb',
    messagingSenderId: '97884437874',
    projectId: 'fir-flutter-codelab-44bee',
    storageBucket: 'fir-flutter-codelab-44bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOU0dkGXwOc0DZt4bK7LkiXrgVysqMC0',
    appId: '1:97884437874:ios:974a7b5d8f313c39da71eb',
    messagingSenderId: '97884437874',
    projectId: 'fir-flutter-codelab-44bee',
    storageBucket: 'fir-flutter-codelab-44bee.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOU0dkGXwOc0DZt4bK7LkiXrgVysqMC0',
    appId: '1:97884437874:ios:5c37c9384464b9f8da71eb',
    messagingSenderId: '97884437874',
    projectId: 'fir-flutter-codelab-44bee',
    storageBucket: 'fir-flutter-codelab-44bee.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
